# configuracion
equipo:
  formacion: '3-3' # '3-3', '3-1-2', '3-2-1',   NO IMPLEMENTADAS :'2-3-1', '2-2-2'
  casaca: 'principal' #'principal' o 'alternativa'
debug:
  level: 'debug' #'debug' o "info" o "error"
assets:
  cancha: 'images/cancha.png'
  sprites: 'images/spritesDefaults.png'
performance:
  framerate: 4
  margenes: 100 #250
