# configuracion
debug:
  level: 'debug' #'debug' o "info" o "error"
usuarios:
  - {name: juan, password: juan}
  - {name: nicolas, password: nicolas}
  - {name: joaquin, password: joaquin}
  - {name: claudio, password: claudio}
  - {name: zidane, password: zidane}
